name: Compute morphometrics on spine-generic


on:
  push:
    branches:
      - nk/test-workflow
  # release:
  #   types: [published]

jobs:
  download_dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.16

      - name: Install git-annex
        uses: jstritch/setup-git-annex@v1
          
      - name: Configure git
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"

      - name: Download test data
        run: |
            git clone https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord.git
            # change current working directory
            cd ${PWD}/contrast-agnostic-softseg-spinalcord
            # checkout to the branch
            git checkout nk/add-post-training-script-to-compute-csa
            # run script
            chmod +x scripts/download_spine_generic_test_data.sh
            source scripts/download_spine_generic_test_data.sh

      - name: Cache dataset
        uses: actions/cache@v4
        with:
          path: contrast-agnostic-softseg-spinalcord/data-multi-subject
          key: ${{ runner.os }}-data-multi-subject-${{ hashFiles('contrast-agnostic-softseg-spinalcord/scripts/download_spine_generic_test_data.sh') }}
          restore-keys: |
            ${{ runner.os }}-data-multi-subject-

  compute_csa_batch_1:
    runs-on: ubuntu-latest
    needs: download_dataset

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.16

      # https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/.ci.sh
      - name: Install SCT
        run: |
          # source python/etc/profile.d/conda.sh >> $GITHUB_ENV
          git clone https://github.com/spinalcordtoolbox/spinalcordtoolbox.git
          cd spinalcordtoolbox
          ./.ci.sh -i
          # NB: install_sct edits ~/.bashrc, but those environment changes don't get passed to subsequent steps in GH Actions.
          # So, we filter through the .bashrc and pass the values to $GITHUB_ENV and $GITHUB_PATH.
          # Relevant documentation: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
          cat ~/.bashrc | grep "export SCT_DIR" | cut -d " " -f 2 >> $GITHUB_ENV
          cat ~/.bashrc | grep "export PATH" | grep -o "/.*" | cut -d ':' -f 1 >> $GITHUB_PATH

      # - name: Check SCT dependencies
      #   run: sct_check_dependencies

      - name: Restore cached dataset
        uses: actions/cache@v4
        with:
          path: contrast-agnostic-softseg-spinalcord/data-multi-subject
          key: ${{ runner.os }}-data-multi-subject-${{ hashFiles('contrast-agnostic-softseg-spinalcord/scripts/download_spine_generic_test_data.sh') }}
          restore-keys: |
            ${{ runner.os }}-data-multi-subject-        
      
      - name: Run morphometric analysis
        shell: bash -el {0}  # Ensures the Conda environment is properly loaded
        run: |
          git clone https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord.git
          # change current working directory
          cd ${PWD}/contrast-agnostic-softseg-spinalcord
          # checkout to the branch
          git checkout nk/add-post-training-script-to-compute-csa
          # define list of 4 subjects
          subjects=("sub-barcelona06" "sub-beijingPrisma01" "sub-beijingPrisma02" "sub-brnoCeitec04")
          # restore cached dataset
          cp -r ${{ runner.tool_cache }}/contrast-agnostic-softseg-spinalcord/**/data-multi-subject contrast-agnostic-softseg-spinalcord/
          # print the contents of the current working directory
          ls -la
          # run script
          chmod +x scripts/compute_morphometrics_spine_generic.sh
          source scripts/compute_morphometrics_spine_generic.sh "${subjects[@]}"

      - name: Upload batch processing results
        uses: actions/upload-artifact@v4
        with:
          name: csa-results-batch-1
          path: contrast-agnostic-softseg-spinalcord/logs_results

  compute_csa_batch_2:
    runs-on: ubuntu-latest
    needs: download_dataset

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.16

      # https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/.ci.sh
      - name: Install SCT
        run: |
          # source python/etc/profile.d/conda.sh >> $GITHUB_ENV
          git clone https://github.com/spinalcordtoolbox/spinalcordtoolbox.git
          cd spinalcordtoolbox
          ./.ci.sh -i
          # NB: install_sct edits ~/.bashrc, but those environment changes don't get passed to subsequent steps in GH Actions.
          # So, we filter through the .bashrc and pass the values to $GITHUB_ENV and $GITHUB_PATH.
          # Relevant documentation: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
          cat ~/.bashrc | grep "export SCT_DIR" | cut -d " " -f 2 >> $GITHUB_ENV
          cat ~/.bashrc | grep "export PATH" | grep -o "/.*" | cut -d ':' -f 1 >> $GITHUB_PATH

      - name: Check SCT dependencies
        run: sct_check_dependencies

      - name: Run morphometric analysis
        shell: bash -el {0}  # Ensures the Conda environment is properly loaded
        run: |
          git clone https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord.git
          # change current working directory
          cd ${PWD}/contrast-agnostic-softseg-spinalcord
          # checkout to the branch
          git checkout nk/add-post-training-script-to-compute-csa
          # define list of 4 subjects
          subjects=("sub-brnoUhb01" "sub-cardiff03" "sub-cmrra02" "sub-cmrra05")
          # run script
          chmod +x scripts/compute_morphometrics_spine_generic.sh
          source scripts/compute_morphometrics_spine_generic.sh "${subjects[@]}"

      - name: Upload batch processing results
        uses: actions/upload-artifact@v4
        with:
          name: csa-results-batch-1
          path: contrast-agnostic-softseg-spinalcord/logs_results          